### ISSUE TITLE
FOR every 10 you buy, you get 1 free

### ISSUE THREAD

**Issue by nschneid** [carmls/snacs-guidelines#1]
A rate based on iterating over a set.

Reminiscent of:

* Frequency—but not temporal
* RateUnit—PER = 'for each/every'. But what if we want to label just the FOR?

**Comment by nschneid** [comment]
[Reddit task_001:997]

**Comment by jdch00** [comment]
Any reason that "for_every" should be considered as a single target marked as RateUnit?
para_cada i guess in spanish... 

If not, then we need a label that allows for correspondence (#70 above) --- "as applied to" sense.

**Comment by nschneid** [comment]
This is hard. Let me discuss this one with Jena and @svivek in our next meeting.

**Comment by nschneid** [comment]
Aryaman: Exchange sense of FOR? Because you are being rewarded.

Removing the notion of rate which comes from "every":
- For your purchase of 10 puppies, you get 1 free.

However "for each" and "for every" seem pretty idiomatic as ways to express rate. Should they be MWEs?

For almost every bird I see I know what kind it is. (a regularity of correspondence, not necessarily a *rate*)
(paraphrase: Whenever I see a bird I usually know what kind it is.)

Maybe the word "rate" is our problem, because it suggests a numeric quantity, and we should just interpret RateUnit as a relationship of recurrence.

**Comment by nschneid** [comment]
Another tricky one: "on average" (_It takes people an hour **on average**_).

I wonder if we should generalize `RateUnit` to something like `SetIteration` (whose temporal counterpart is `Frequency`).

Could also apply to "in general" (#25).

**Comment by nschneid** [comment]
Or we could simply broaden `Extent` to cover `RateUnit` and these other set-wise quantifiers.

**Comment by nschneid** [comment]
After discussion with @jenahwang: SetIteration seems better than RateUnit; concerned about overloading Extent too much.

**Comment by nschneid** [comment]
Just to throw out another option: if `RateUnit` or `SetIteration` is hard to justify because it's so sparse, what about applying the label `Configuration` for some miscellaneous cases just as we do for `Temporal`?

**Comment by nschneid** [comment]
> Just to throw out another option: if `RateUnit` or `SetIteration` is hard to justify because it's so sparse, what about applying the label `Configuration` for some miscellaneous cases just as we do for `Temporal`?

Per @jenahwang, it's more frequent for Korean since the equivalents of "each"/"every" are adpositional.

Renaming `RateUnit` -> `SetIteration` seems like a good option.
