### ISSUE TITLE
one 'S planet

### ISSUE THREAD

**Issue by esmanning** [carmls/snacs-guidelines#104]
'my/his planet' shows up repeatedly throughout The Little Prince. We've been labeling it as Gestalt, which makes sense in real life (~ my address), but increasingly feel that in the universe of the book where each person essentially has their own planet, it might be more akin to someone's house and therefore Possessor. Where do we draw that line?

**Comment by nschneid** [comment]
I'd choose one and be consistent. :)

**Comment by esmanning** [comment]
We've been sticking with Gestalt.

**Comment by aryamanarora** [comment]
Going to put this here for future generations:
![](https://cdn.discordapp.com/attachments/600693659926659085/735894935135322142/Screen_Shot_2020-07-23_at_12.23.17_PM.png)
