### ISSUE TITLE
appear IN the full radiance...

### ISSUE THREAD

**Issue by esmanning** [carmls/snacs-guidelines#109]
> It was only IN the full radiance of her beauty that she wished to appear.
lpp_8
sent_id = lpp_1943.380

A weird sentence! Characteristic\~Locus? Circumstance\~Locus?

**Comment by nschneid** [comment]
My gut reaction is Circumstance for the scene role. Manner is also a possibility. Definitely figurative/flowery; trying to pin down a literal relation may not work.

**Comment by nschneid** [comment]
Too flowery of a metaphor—let's just go with Locus.
