### ISSUE TITLE
time FOR breakfast

### ISSUE THREAD

**Issue by esmanning** [carmls/snacs-guidelines#110]
> "I think it is time FOR breakfast"
lpp_8
sent_id = lpp_1943.394

Seems almost Purpose-y but maybe not quite (it's more like a time that's appropriate for breakfast, rather than time set aside for the purpose of eating breakfast). Also sort of but not quite like the occasion use of Circumstance ("I had peanut butter for lunch")

**Comment by nschneid** [comment]
Is this specific to the "it is time for X" construction? Alternates with infinitive: "It is time to eat breakfast"

What about "there is (no/insufficient) time for X"—same or different?

**Comment by esmanning** [comment]
"no/insufficient time for" feels more Purposey to me than this does?

**Comment by nschneid** [comment]
Poked around in EWT and GUM for a bit. "It BE time (for X/to X/that X)" is well-attested and a unique idiom AFAICT. 

Note that this is not a cleft: By contrast, "It is old news that X" can be rewritten as "That X is old news".

**Comment by nschneid** [comment]
Going with Theme for now. While this construction is special, "time" in relation to the PP reminds me of "reason": syntactically you can also have "a reason for X/to X/that X".
