### ISSUE TITLE
obstructed BY

### ISSUE THREAD

**Issue by esmanning** [carmls/snacs-guidelines#113]
> The little prince looked everywhere to find a place to sit down; but the entire planet was crammed and obstructed BY the king's magnificent ermine robe.
lpp_10
sent_id = lpp_1943.491

Couldn't decide whether this is Instrument\~Causer or plain Causer

**Comment by esmanning** [comment]
All the worst things involve force dynamics, it seems

**Comment by nschneid** [comment]
Since there is no implication that somebody was using the robe for obstruction, I think not Instrument. Going with plain Causer.
