### ISSUE TITLE
raise IN salute

### ISSUE THREAD

**Issue by esmanning** [carmls/snacs-guidelines#115]
> It is [a hat] to raise IN salute when people acclaim me.
lpp_11
sent_id = lpp_1943.612

> The conceited man raised his hat IN a modest salute.
sent_id = lpp_1943.617

> The conceited man against raised his hat IN salute.
sent_id = lpp_1943.620

Characteristic\~Locus? Manner? Purpose?

**Comment by nschneid** [comment]
Yesterday I wrote the phrase "the emergence of a new paradigm IN neural networks driven by large pretrained contextualized language models". I.e. neural networks constitute a new paradigm. Identity-ish, maybe? Is this the same sense?

**Comment by nschneid** [comment]
Oh is this the "you have a friend IN me" sense?

**Comment by esmanning** [comment]
I wouldn't say that the hat IS the salute - maybe the act of raising IS the salute, but that doesn't feel quite like any other Identity examples.

**Comment by nschneid** [comment]
I definitely think the raising of the hat is being characterized as a salute. "raise it BY WAY OF a salute" would have the same meaning I think. Maybe it's a specific meaning of "X action should be interpreted as a speech act of type Y".

What about "raise it AS a salute"?

Is "a salute" a good answer to "How did he raise his hat?"? For a typical Manner it would be, though it may not be a perfect test.

**Comment by esmanning** [comment]
I think the Manner reading is possible - there are multiple ways to raise a hat, not all of which would qualify as a salute, so you could conceivably follow up "he raised his hat" with "how did he raise it?" if you want to know if it was a salute. But it's not necessarily the best reading.

**Comment by nschneid** [comment]
IN is generally a better fit to Manner than Purpose, for example.

**Comment by aryamanarora** [comment]
I think dynamic verb "raise" being there rules out Characteristic~Locus right?

**Comment by nschneid** [comment]
Manner seems reasonable enough
