### ISSUE TITLE
belong TO

### ISSUE THREAD

**Issue by esmanning** [carmls/snacs-guidelines#116]
e.g.
> The fourth planet belonged TO a businessman.
lpp_13
sent_id = lpp_1943.649

belong_to seems like a somewhat idiosyncratic use of TO, so perhaps an MWE?

If not: the scene role is Possessor, but what's the function? TO is often Goal, but intuitions differed on whether there's anything Goal-ish in this. If not, maybe Possessor\~Theme?

**Comment by nschneid** [comment]
It occurs once in STREUSLE and is treated as an MWE.

**Comment by aryamanarora** [comment]
Potential multilingual connection: Dravidian languages and some Indo-Aryan languages (including Dakhini, a southern dialect of Hindi-Urdu) prototypically use the dative case for possession, which is parallel to TO here. Maybe Possessor~Goal is not a bad label then, and I guess it could be construed as a kind of fictive motion.

**Comment by nschneid** [comment]
@aryamanarora In those languages, what verb is used for predicative possession? Something like "be", or "belong"?

**Comment by nschneid** [comment]
"Belong" inflects as a full verb, so this is more of a prepositional verb than a multiword preposition.

**Comment by aryamanarora** [comment]
@nschneid In Indo-Aryan, the copula. In Dravidian, I don't think they use copulas generally so nothing I presume.

Couple examples from Masica (1999):
* (Marathi) gāī-**lā** śinga āhet / cow-**DAT** horn.PL be.PRS / A cow has horns.
* (Sindhi) mū̃ **khē** ba ghar<sup>a</sup> āhin / I-**DAT** two house.PL be.PRS / I have two houses.

**Comment by nschneid** [comment]
Possessor~Goal seems good
