### ISSUE TITLE
make a mistake IN

### ISSUE THREAD

**Issue by esmanning** [carmls/snacs-guidelines#118]
> He made the most frightful noise that resounded all over the place, and I made four mistakes IN my addition.
lpp_13
sent_id = lpp_1943.675

> And never would they make a mistake IN the order of their entry upon the stage.
lpp_16
sent_id = lpp_1943.928

There seems to be an ambiguity between IN modifying MAKE (Circumstance?) or IN modifying MISTAKE (Topic?)

**Comment by nschneid** [comment]
For STREUSLE purposes I'd say make+mistake is a light verb construction. But yes, there's a static concept of wrongness and there's an act of erring, and the IN-PP could be with respect to either. Is it made four mistakes *when performing addition* or made four *addition mistakes* / *mistakes OF addition*? Seems like one of those benign ambiguities where both interpretations work out to the same thing in the real world.

*Mistake* feels like a shell noun: it needs some sort of content which is the thing that was done wrong(ly). I think I would lean toward Topic. Circumstance makes it sound like the addition could be incidental background to the act of making a mistake, which is probably not the intention.

**Comment by nschneid** [comment]
Going with Topic (not too far from "excel IN something")
