### ISSUE TITLE
OVER the six continents

### ISSUE THREAD

**Issue by esmanning** [carmls/snacs-guidelines#124]
> To give you an idea of the size of the Earth, I will tell you that before the invention of electricity it was necessary to maintain, OVER the whole of the six continents, a veritable army of 462,511 lamplighters for the street lamps.
lpp_17
sent_id = lpp_1943.921

Annotators had different intuitions on whether this OVER expresses fictive motion warranting Locus\~Path, or if it's a statement about a set with no fictive motion (something involving Whole)

**Comment by nschneid** [comment]
Similar: ACROSS, THROUGHOUT

Feels more Locus-y than Whole-y to me: it explains where the lamplighters are.

**Comment by nschneid** [comment]
Going with Locus~Path
