### ISSUE TITLE
lamplighters OF a place

### ISSUE THREAD

**Issue by esmanning** [carmls/snacs-guidelines#126]
> First would come the turn of the lamplighters OF New Zealand and Australia.
lpp_16
sent_id = lpp_1943.924

Repeated several times in the chapter for lamplighters OF various countries and continents.

Unsure whether this means the lamplighters located IN those places (Locus\~Gestalt) or something more like those who are employed to light lamps in/by the countries (Gestalt?)

i.e., if a New Zealand lamplighter goes to another continent on vacation, is he still in the set of lamplighters OF New Zealand while not physically located there?

**Comment by nschneid** [comment]
I would not overthink this one. Seems reasonable to interpret this as the lamplighters who are in these countries.

**Comment by nschneid** [comment]
Going with Locus~Gestalt
