### ISSUE TITLE
COME UP TO as measure of height

### ISSUE THREAD

**Issue by esmanning** [carmls/snacs-guidelines#127]
> The only mountains he had ever known were the three volcanoes, which CAME UP TO his knees.
lpp_19
sent_id = lpp_1943.1008

A metaphor of motion used to describe a (potentially static) property. Also unsure if this is an MWE, and if so whether it's COME_UP_TO or just UP_TO (which can also be used similarly with 'be', e.g. "this grass is up to my knees" but maybe not any other verbs)

Just occurred to me you can also use {is/comes} DOWN TO, at least to describe hair length.

**Comment by nschneid** [comment]
Yes, verbal metaphoric sense of 'come', similar to the static sense of 'reach' (her hair reaches her knees).

I think UP and DOWN are Direction modifiers of the to-PP, not strictly necessary for this sense of 'come':

- her hair comes to her shoulders (perhaps a bit old-fashioned sounding)
- her hair comes right to her shoulders (sounds better to me)
- her hair comes (right) down to her shoulders

And I think the TO plausibly marks a (fictive motion) Goal; while it is probably statistically collocated with this sense of 'come' I think you could omit it with the right context:

- How far (down) does her hair come?

So I'd probably think of this as a special sense of 'come', not an MWE.

**Comment by aryamanarora** [comment]
What about Extent? Just encountered this same issue in Hindi with *tak* which tends to be Extent or Goal.

**Comment by nschneid** [comment]
It's a perspective on an extended item. But "his kness" is not the Extent, it's the endpoint of the Extent.

**Comment by aryamanarora** [comment]
Yeah true, we went with Goal~Extent since we don't think Goal is a prototypical meaning of *tak* anymore, and this use most literally seems to be fictive motion Goal.

**Comment by nschneid** [comment]
Decision: came up/Locus~Direction to/Locus~Goal his knees
