### ISSUE TITLE
IN oneself

### ISSUE THREAD

**Issue by esmanning** [carmls/snacs-guidelines#128]
> But IN herself alone she is more important than all the hundreds of you other roses.
lpp_21
sent_id = lpp_1943.1168

This seems like a Reflexive PP Idiom as in 6.5.2 of guidelines, but those only cover 'FOR oneself' and 'BY oneself' constructions.

**Comment by aryamanarora** [comment]
Also found in Hindi, अपने में "REFLEXIVE LOC". I had labelled it Characteristic~Locus, but not confidently.

**Comment by nschneid** [comment]
As far as I can tell, this is some sort of focus marking. Labeling as discourse.
