### ISSUE TITLE
waste time OVER something

### ISSUE THREAD

**Issue by esmanning** [carmls/snacs-guidelines#131]
> They waste their time OVER a rag doll and it becomes very important to them
lpp_22
sent_id = lpp_1943.1204

I think this is an older construction that's now only marginally grammatical - I would waste time ON or WITH something, but not OVER.

Waste time WITH is Theme according to the guidelines, but OVER is not prototypically Theme. Maybe Topic, which can be used with OVER (argue over, think over)?

**Comment by nschneid** [comment]
Seems like Topic to me.
