### ISSUE TITLE
X minutes IN every week

### ISSUE THREAD

**Issue by esmanning** [carmls/snacs-guidelines#132]
> With these pills, you save fifty-three minutes IN every week
lpp_23
sent_id = lpp_1943.1214

Similar to #1, but more temporal. Time? Locus? Frequency? Whole?

**Comment by nschneid** [comment]
Though the quantifier "every" provides frequency semantics to the NP, I don't think it's a Frequency PP. If you select one particular week those fifty-three minutes saved are in that week, correct?

**Comment by esmanning** [comment]
Correct!

**Comment by nschneid** [comment]
So we can say 53 minutes OF/IN/OUT_OF the week. Ideally these would have the same scene role but different functions?

For the scene role I'm vacillating between Time and Whole. I guess technically Whole is better because a time period is a portion of another time period.

**Comment by esmanning** [comment]
Time\~Whole is also tempting (used for some other "time in time" constructions like "the 15th of March"), but then we'd lose the ability to change function based on the preposition.

**Comment by nschneid** [comment]
OF can have Whole as a function, but off the top of my head we don't have precedent for IN with Whole as a function.

**Comment by aryamanarora** [comment]
Why not Time~Time? We do use Time to pick out something that takes place over a span, e.g. "I worked for fifty-three minutes DURING the week" is unambiguously Time. (Although, perhaps on a tangent, I think the functions of DURING and AT/ON temporally should probably be split up.)

**Comment by aryamanarora** [comment]
Alternatively, IN_EVERY behaves like PER.

**Comment by nschneid** [comment]
Going with Time. Whole seems like overkill
