### ISSUE TITLE
spring OF fresh water

### ISSUE THREAD

**Issue by esmanning** [carmls/snacs-guidelines#133]
> if I had fifty-three minutes to spend as I liked, I should walk at my leisure toward a spring OF fresh water
lpp_23
sent_id = lpp_1943.1217

(A spring seems to be the point where water comes from the ground, so not exactly the same as other bodies of water)

Scene role seems to be Characteristic. Construals of OF would normally be Characteristic\~Identity or Characteristic\~Stuff, but neither feels like a great fit?

**Comment by nschneid** [comment]
A spring consists of/contains water, right? Characteristic~Stuff feels reasonable to me

**Comment by esmanning** [comment]
Maybe, but doesn't seem like as clear-cut a case of containment as the guidelines examples, so we weren't sure!

**Comment by aryamanarora** [comment]
field OF wheat, I think occurs later on and is also not obviously a container

**Comment by nschneid** [comment]
> field OF wheat, I think occurs later on and is also not obviously a container

I would think that's Stuff

**Comment by nschneid** [comment]
https://www.youtube.com/watch?v=DHLlM8Z7fAc

**Comment by aryamanarora** [comment]
I lost it at "rented family"

**Comment by nschneid** [comment]
Decision: Characteristic~Stuff
