### ISSUE TITLE
Age as Characteristic

### ISSUE THREAD

**Issue by aryamanarora** [carmls/snacs-guidelines#140]
> छः साल **का** बच्चा
> _chaḥ sāl **kā** baccā_
> six years **GEN** child
> "six-year-old child"

(Note that the noun "age" is not in here at all.) For whatever reason I labelled this QuantityValue before. Not so certain about that now. Nitin has suggested Characteristic~QuantityValue.

Is the QuantityValue even necessary? It doesn't seem much like a unit to me ("how much child do you have?" "six years") but it is _[entity] of [quantity] [unit]_ which does fit that supersense syntactically it seems. The alternative is Characteristic~Identity.

**Comment by esmanning** [comment]
Is this equivalent to English "a child OF 5 (years)"? That's in English guidelines (§ 6.6) as Characteristic

**Comment by nschneid** [comment]
Yeah plain Characteristic as in English is probably the best. If it were "a distance OF 1000 yards" (is this in the English guidelines?) I could see QuantityValue~Identity. But the child's age is not being equated with the child quite like the measure is being equated with the distance.

**Comment by aryamanarora** [comment]
That makes sense. "of" can only be Characteristic~Identity though right?

**Comment by nschneid** [comment]
Per #141 we should change other uses of OF in this sense to also be plain Characteristic.

**Comment by nschneid** [comment]
Adding "a distance of 10m" (mentioned above) and "a height of 10m" (alluded to in #108) as plain `Identity`, analogous to  and "the age of 8".

**Comment by nschneid** [comment]
"a child of 5" is already plain `Characteristic`: http://www.xposition.org/en/ages/
