### ISSUE TITLE
scalar AHEAD_OF, BEHIND: ComparisonRef vs. Locus

### ISSUE THREAD

**Issue by nschneid** [carmls/snacs-guidelines#20]
Team A is AHEAD_OF Team B: Is this just Locus (as if they were literally standing in line)? Or maybe ComparisonRef~>Locus, because there is a nonspatial comparison being made? Cf. "the temperature is ABOVE / GREATER_THAN 30 degrees".

[Reddit task_007:671]

**Comment by nschneid** [comment]
"Christian countries that are not far BEHIND some of the worse Islamic countries in terms of human rights" [Reddit task_000:1460]

**Comment by nschneid** [comment]
Team A is AHEAD_OF Team B: ComparisonRef~>Locus

A win in the game will put Team A IN_FRONT_OF Team B in the tournament: Goal???

**Comment by svivek** [comment]
Cf. A win in the game will put Team A at the top of the ranking.

**Comment by dhwang90** [comment]
All these would be plain ComparisonRef in Korean
산A가 산B**보다** 높다 - mountain A is higher/taller than mountain B
집A**보다** 큰 집 - house that is bigger than house A
팀A가 팀B**보다** 앞섰다  - team A is ahead of team b (in the tournament)

**Comment by svivek** [comment]
I prefer this restaurant OVER that one. ComparisonRef~>Locus (from guidelines)
The win placed team A OVER team B?

**Comment by nschneid** [comment]
Conclusion: Relative spatial position metaphor for an explicit comparison of multiple things should be ComparisonRef~>Locus.

**Comment by svivek** [comment]
Spatial | Relative vs Absolute | Supersense
-------|----------------------|-------------
Yes      | Relative                      | Locus 
No       | Relative                      |  ComparisonRef~>Locus
Yes      | Absolute                      | Locus 
No       | Absolute                      |  ComparisonRef~>Locus

**Comment by nschneid** [comment]
I think we need to revisit this to see if we can draw a line for what counts as spatial. Recall that we removed Value and merged scalar "locations" in with Locus. I'm worried we'll end up with something inconsistent if we start treating abstract *relative* spatial metaphors—above, below, ahead_of, behind, over, under—differently from *coincidental* spatial metaphors—at, in, on.

Numerical scale:
- 10 BELOW zero (reviews-219262-0005)
  * cf. The temperature was AT 0 degrees.
- BELOW my budget (reviews-182354-0003)
  * cf. WITHIN my budget
- They came in UNDER a lot of other quotes (reviews-043020-0018)

Evaluative scale metaphor:
- ABOVE the satisfactory mark (reviews-145645-0003)
  * cf. AT the satisfactory mark

Scale of "progress":
- Team A is AHEAD_OF Team B
- "Christian countries that are not far BEHIND some of the worse Islamic countries in terms of human rights"

Preference:
- I generally like the BK OVER the other fast serving restaurants (reviews-068436-0002)

Place in discourse/conversation: 
- The comment BELOW (reviews-257296-0003)
- the BELOW bad experience (reviews-290594-0001)

**Comment by nschneid** [comment]
I am coming around to the relative/absolute distinction. One property of the **relative** ones is that a similar item OR a value can be the comparand:

- Your heart rate is BELOW 100 bpm.
- Your heart rate is BELOW mine.

Which is not true of absolute prepositions:

- Your heart rate is AT 100 bpm.
- \*Your heart rate is AT mine.

Or of Approximators:

- I have OVER 3 eggs.
- \*I have OVER yours eggs.

**Comment by nschneid** [comment]
Draft new section under ComparisonRef:

![image](https://user-images.githubusercontent.com/985263/75116099-dd565e80-5632-11ea-9183-1c2b94bd4483.png)
![image](https://user-images.githubusercontent.com/985263/75116100-e3e4d600-5632-11ea-9117-53fb9b2ec8fa.png)

**Comment by nschneid** [comment]
Draft addition under ComparisonRef:

<img src="https://user-images.githubusercontent.com/985263/75116170-99b02480-5633-11ea-8bee-1732f2f42815.png" width="400"/>

<img src="https://user-images.githubusercontent.com/985263/75116158-708f9400-5633-11ea-8310-b3b0b7f2b97f.png" width="400"/>

**Comment by nschneid** [comment]
Or should "reading at a fifth grade level" be Manner~>Locus?

**Comment by nschneid** [comment]
NEW ATTEMPT

<img src="https://user-images.githubusercontent.com/985263/75119140-341d6180-564e-11ea-9e24-eca03415004c.png" width="400"/>
<img src="https://user-images.githubusercontent.com/985263/75119141-35e72500-564e-11ea-9fd6-8126e3a98351.png" width="400"/>

**Comment by nschneid** [comment]
Remove the Manner~>Locus examples, which are complicated.
