### ISSUE TITLE
result IN

### ISSUE THREAD

**Issue by nschneid** [carmls/snacs-guidelines#22]
Cause will result IN Effect

[Reddit task_004:308]

**Comment by svivek** [comment]
https://uvi.colorado.edu/verbnet/result-27.2

**Comment by nschneid** [comment]
Causer and Theme as scene roles for causation verbs?

Maybe we should consider subdividing Theme for events.

**Comment by nschneid** [comment]
cf. aspectual verbs, start/end WITH

**Comment by nschneid** [comment]
Theme~>Theme (cf. decrease IN food cravings)
