### ISSUE TITLE
happen TO somebody/something

### ISSUE THREAD

**Issue by nschneid** [carmls/snacs-guidelines#24]
"The same (thing) happened TO me"

Theme? Experiencer? Beneficiary? How much should we rely on the context to decide?

[Reddit task_004:964]

**Comment by nschneid** [comment]
"What happened TO the book?" is ambiguous: a way of saying "Where did the book go?" OR "How was the book affected?"

**Comment by nschneid** [comment]
Theme~>Theme (cf. a repair TO the air conditioning)

**Comment by svivek** [comment]
Experiencer/Beneficiary assume animacy.
