### ISSUE TITLE
see X AS being Y

### ISSUE THREAD

**Issue by esmanning** [carmls/snacs-guidelines#41]
"I see children as being innocent creatures"

Characteristic~Identity or just Identity? 

It's not quite the typical syntax for either: 
* similar to guidelines examples of Characteristic~Identity like "She described him as sad", but that's for secondary predicate adjectives
* Identity would normally have a nominal object

**Comment by nschneid** [comment]
"She described him as sad" and "She described him as being sad" feel pretty much the same to me. I'd go with Characteristic~>Identity
