### ISSUE TITLE
inherent TO

### ISSUE THREAD

**Issue by esmanning** [carmls/snacs-guidelines#42]
"harmful mental conditioning is inherent TO religious behavior"

**Comment by nschneid** [comment]
cf. inherent IN
endemic TO/IN

**Comment by nschneid** [comment]
specific TO
pertaining TO

**Comment by nschneid** [comment]
native TO

**Comment by nschneid** [comment]
We're thinking just Theme. Hard to see a Goal metaphor. (Maybe this comes from a historical use of the dative for possessor?) @dhwang90?

**Comment by nschneid** [comment]
Theme~>Theme
