### ISSUE TITLE
Surrounded by/in danger.

### ISSUE THREAD

**Issue by jdch00** [carmls/snacs-guidelines#48]
자신들도 모르는 사이**에** 이 위험**에** 둘러싸여 있었다.
self unaware space-**ey** this danger-**ey** surround was.
In the space(time) that they were unaware, the danger surrounded them.
~They were surrounded by danger even before they knew what was going on.

We currently have Circumstance for Scene for both, for the lack of a better label. 
I can sort of see Time for the first **ey**, what exactly is the second?

**Comment by nschneid** [comment]
[The leaves]Theme (that have fallen) surround [the tree]Theme.

[The tree]Theme is among [the leaves]Locus.

**Comment by jdch00** [comment]
이 무더위에 어떻게 지냈니?
this  heat-in how pass-time ? 
'How have you been (fairing) in this heat?'

**Comment by nschneid** [comment]
https://youtu.be/7Y-KvoKjCD0?t=65

**Comment by jdch00** [comment]
Locus ~> Circumstance
