### ISSUE TITLE
advantages OVER

### ISSUE THREAD

**Issue by esmanning** [carmls/snacs-guidelines#54]
> ... any kind of new tank can only guarantee the needed advantages OVER the enemy for a maximum of one year ...

Our best guess was ComparisonRef~Locus, but it's not quite the same as the 'prefer X OVER Y' meaning that that construal is normally used for.

Source:
Reddit task_016
new_doc id = 25482047-59d8-2aaa-da4b-25cd20b9e029
sent_id = 8

**Comment by nschneid** [comment]
This is about having an advantage (~power) over someone.

SNACS is not very good at force dynamics like this.

**Comment by nschneid** [comment]
(Is there a scale in the construal of having an advantage OVER someone? Maybe not in my default reading.)

**Comment by nschneid** [comment]
ComparisonRef~>Locus seems good enough given that we don't have a good treatment of force dynamics.
