### ISSUE TITLE
responsible FOR

### ISSUE THREAD

**Issue by esmanning** [carmls/snacs-guidelines#55]
> The JavaScript part of the plugin is responsible FOR both writing out the quiz form and validating it

We were surprised not to find previous examples of or guidelines for this! Theme? Topic?

Reddit task_016
new_doc id = e4beae2e-a4f8-cbd8-0481-f06c77b30256
sent_id = 2

**Comment by nschneid** [comment]
Topic seems plausible

**Comment by nschneid** [comment]
Kind of modal (obligation). Theme is probably best.
