### ISSUE TITLE
hypothesis FOR a measurement

### ISSUE THREAD

**Issue by esmanning** [carmls/snacs-guidelines#57]
> You can doubt the hypothesis FOR a measurement but you can not doubt the actual measurement.

A little unsure of what relationship between hypothesis and measurement is being described here (the hypothesis that led to the measurement being made, assuming scientific method? or a hypothesis made based on a measurement?). Tentatively decided on Purpose; other possibilities discussed included Circumstance and ??.

Reddit task_016
new_doc id = 55c36c3d-5cbb-c080-3547-5c5ef76dce6e
sent_id = 4

**Comment by nschneid** [comment]
Without more context I definitely don't understand this.

**Comment by esmanning** [comment]
Upon further debate we decided this is ambiguous between Purpose and Explanation readings, so went with the more general Explanation.
