### ISSUE TITLE
x dollars IN 2014 dollars IN reparations

### ISSUE THREAD

**Issue by esmanning** [carmls/snacs-guidelines#58]
> Germany lost 442 million dollars (IN 2014 dollars) IN war reparations after World War I.

We struggled, separately, with each of these 'in's, and tentatively tagged both as Identity. Other possibilities discussed included RateUnit or Stuff for the first, and Explanation~Locus for the second.

Reddit task_016
new_doc id = 822a6610-17cb-7e18-eba5-a923d7386d6c
sent_id = 3

**Comment by nschneid** [comment]
- I think the first one is for a unit of measurement; cf. *What is the desk's height IN inches?* Feels like Characteristic~>Locus might apply but I'm not sure.
- *Lost millions of dollars IN war reparations*: are war reparations the manner in which money was lost? Or is this equivalent to *millions of dollars OF war reparations*?

**Comment by nschneid** [comment]
cf. pay in cash (Instrument~>Manner)

**Comment by jdch00** [comment]
lost million of dollars IN war reparations 
-- lost money doing war reparations
lost million of dollars OF war reparations
-- lost war reparations money
lost millions of dollars TO war reparations
-- lost money doing war reparations

owe millions of dollars IN war reparations
-- owe war reparations (millions dollars worth)
owe millions of dollars OF war reparations
-- owe war reparations money
owe millions of dollars TO war reparations
-- there is an ongoing war reparations and money is owed to that.

**Comment by nschneid** [comment]
DECISION: For units of measure IN, add to "form or shape" subclass of Characteristic~>Locus.

**Comment by nschneid** [comment]
Identity: IN reparations ≈ AS reparations? or IN THE FORM OF reparations?

**Comment by nschneid** [comment]
cf. http://flat.nert.georgetown.edu/en/in/Identity--Identity/

"I see a future president in you": Identity, or Locus-esque?

**Comment by svivek** [comment]
I see you AS a future president.: Identity

**Comment by jdch00** [comment]
"He's holding back, he's hiding
But what, I can't decide
Why won't he be the king I know he is?
The king I see inside?" <---??

**Comment by nschneid** [comment]
cf. millions of dollars IN interest

**Comment by nschneid** [comment]
IN escrow

**Comment by nschneid** [comment]
Good example of many possible construals of a relation:

millions of dollars IN/OF/FOR/TO/?AS reparations

**Comment by nschneid** [comment]
There may be a construction here that takes the units sense of IN (millions IN cash) and extends it to the purpose of spending (millions IN reparations).

**Comment by nschneid** [comment]
Characterstic~>Locus
