### ISSUE TITLE
ABOVE a value

### ISSUE THREAD

**Issue by esmanning** [carmls/snacs-guidelines#59]
> If it's ABOVE 126 mg/dL it's most likely diabetes
task_014
new_doc id = 7b5a3de5-095f-02aa-80c6-c7032b9b017c
sent_id = 4

Settled on Approximator (cf. 'over 3 eggs' in guidelines), but also wondered if 'above' was locusier enough to warrant Approximator~Locus

**Comment by nschneid** [comment]
Hmm. My gut feeling is this is just Locus: 126 mg/dL is a specific point on a scale, as is "it" (the unknown blood sugar measurement?), and the relation between them is that the former is above the latter. This is like saying "5 is greater than 4".

An Approximator usually establishes a **range** on a scale in reference to one of its bounds: "It cost OVER 10 dollars" doesn't specify an exact cost, but identifies an open interval of all costs exceeding $10. BETWEEN X and Y forms a closed interval between two points. ABOUT forms a fuzzy range around the specific point.

Note that you wouldn't normally say "I bought ABOVE a dozen eggs" or "I drank ABOVE a gallon of water"; you would say OVER. This special construction with P + measurement + N selects for Approximators.

**Comment by nschneid** [comment]
Another option is that what we call Approximator is really about a cluster of related constructions that use a subset of Locus prepositions to talk about scalar ranges. We COULD decide that "Approximator" is really more of a syntactic label than a semantic one.

**Comment by nschneid** [comment]
NEW DRAFT GUIDELINES

<img src="https://user-images.githubusercontent.com/985263/75121549-10b0e180-5663-11ea-8b4d-b2f37566e046.png" width="400"/>

**Comment by nschneid** [comment]
"without directly connecting" -> "without establishing a relation"

**Comment by nschneid** [comment]
let's change "3 eggs" to "a dozen eggs", as it sounds weird to approximate such a precise number

**Comment by nschneid** [comment]
In general, in copular sentences, the Approximator reading of the complement is dispreferred.

**Comment by nschneid** [comment]
"(446) features a copular sentence with a preposition at the beginning of a predicate complement. In cases like this, is arguably ambiguous whether the preposition acts as a modifier of the quantity, which would suggest Approximator, or establishes a relation between subject and predicate, which would suggest ComparisonRef~>Locus. In general we prefer the latter analysis."
