### ISSUE TITLE
puts [metaphorical] weight ON

### ISSUE THREAD

**Issue by esmanning** [carmls/snacs-guidelines#61]
> Dash charging is only where you bring a Dash charger .
And it puts more weight ON having a proper cable there , too .
task_014
new_doc id = bd143fa9-b714-210c-665d-7435c1066932
sent_id = 3

Clearly not literal weight, more like 'puts importance on' 
Goal\~Locus? Circumstance\~Locus? Something else?

**Comment by nschneid** [comment]
Is *put weight on* 'emphasize' an MWE?

- Can you talk about emphasis with a weight metaphor but not those precise words (e.g., take weight off, shove burden onto, ...)?
- Can you use *put weight* with this meaning but omit the *on*?
  * He puts a lot of weight on getting good grades. / ?How much weight does he put? ?Where does he put the most weight? ?Why does he put so much weight there?

**Comment by esmanning** [comment]
Good point - we made this MWE.
