### ISSUE TITLE
year AFTER year

### ISSUE THREAD

**Issue by esmanning** [carmls/snacs-guidelines#62]
> So, beginning in 1850 and continuing year AFTER year, ships started to come.
task_014
new_doc id = 3933b869-63a2-1dde-5dee-5ff366bc9bae
sent_id = 4

We considered MWE, but this type of 'after' can definitely be used with other words (day after day, etc.)

Settled tentatively on Time, because it does have a literal meaning of years coming after other years, but not totally convinced. There was also a suggestion that there might be something along the lines of Frequency or RateUnit going on?

**Comment by nschneid** [comment]
Maybe Frequency. Cf. "year BY year", "year IN and year OUT"

**Comment by nschneid** [comment]
"year AFTER year" is a cxn that specifies frequency, but the AFTER itself is a sequential time relation, so just Time.

**Comment by nschneid** [comment]
"year BY year" and "year IN and year OUT" are also reduplicative cxns.

Maybe "BY" here is an old sense meaning 'after'? as in passing by. Time?

cf. step BY step, etc., where we are following a series of steps of a process. Related to "one at a time"

MWE analysis: year IN_and_  year _out?? then it's hard to see how the lexical pieces compose

**Comment by esmanning** [comment]
"little by little" is another one similar to "step by step" that we just encountered in Little Prince ("It was from words dropped by chance that, little BY little, everything was revealed to me"; sent_id = lpp_1943.106)

We were thinking that "little by little" as a whole seems to mark frequency, but it's not at all clear what the BY itself is doing (maaaaybe it's "little after little" as suggested above and therefore time, but that doesn't feel quite right for this case). Marking it as an MWE would be easier, but it's too productive of a cxn for that.

**Comment by esmanning** [comment]
and yet another: "Bit BY bit I came to understand the secrets of your sad little life" (sent_id = lpp_1943.265)

**Comment by nschneid** [comment]
Work discussing "brick BY brick" and "one BY one": https://www.aclweb.org/anthology/2020.mwe-1.4

**Comment by nschneid** [comment]
Might be a good candidate for the new `SetIteration` label in v2.6. I am going to use `RateUnit` for now.

**Comment by nschneid** [comment]
[Jackendoff 2008](http://muse.jhu.edu/content/crossref/journals/language/v084/84.1jackendoff.pdf) addresses this family of "NPN" constructions where the noun is characteristically repeated: _day after day_, _day by day_, go _house to house_, and so forth. For the productive ones, it seems that most of them involve some notion of set iteration.* I propose we use `SetIteration` for the preposition regardless of whether the nouns are temporal.

The syntactic structure is somewhat unclear as noted by Jackendoff and in CGEL pp. 632-633, but we can just treat it as [NP N [PP P N]] for our purposes.

\* The main exception: _to_ indicating a juxtaposition or opposition of two items, e.g. _face to face_. This is perhaps `Direction`~`Goal`.
