### ISSUE TITLE
proportional TO

### ISSUE THREAD

**Issue by esmanning** [carmls/snacs-guidelines#72]
> The thing that determines the capability of an air force is usually pilot skill which is directly proportional to the number of available flying hours for things like training and exercises
task_015
new_doc id = d138d150-8557-716a-a750-2a812227d96d
sent_id = 1

Is this ComparisonRef~Goal?

**Comment by nschneid** [comment]
"X is proportional to Y" describes a ratio. ComparisonRef doesn't seem like a perfect fit, but it's close. Maybe Theme~>Goal would be better?

**Comment by nschneid** [comment]
ComparisonRef~>Goal seems best.
