### ISSUE TITLE
accompanied WITH / go WITH

### ISSUE THREAD

**Issue by esmanning** [carmls/snacs-guidelines#74]
> Must be accompanied WITH an Erdinger Weißbier 
[Context: recommending a specific Bavarian pork dish]
task_008
new_doc id = 65ff6adc-41ae-f3f7-0010-98240a614be3
sent_id = 5

And

> some would rather just go to a foreign country and actually see and meet foreign people and the different cultures/sights that go WITH it than...
task_009
new_doc id = a1645f58-bb78-eb2d-0ee5-144d8a1d8b42
sent_id = 2

Both of these were previously annotated Accompanier but less clear under 2.5

**Comment by nschneid** [comment]
Verbal reifications of SNACS relations are hard.

Ensemble~>Ancillary, maybe? If we take "accompany" as marking a static relation between two entities.

**Comment by nschneid** [comment]
> Must be accompanied WITH an Erdinger Weißbier

> some would rather just go to a foreign country and actually see and meet foreign people and the different cultures/sights that go WITH it 

Simplified:

"Some want to meet people/sights that go WITH a foreign country."

**Comment by jdch00** [comment]
"visiting foreign country comes WITH it meeting people/seeing sights"

**Comment by nschneid** [comment]
**Ensemble~>Ancillary**
