### ISSUE TITLE
abstract 'bring with'

### ISSUE THREAD

**Issue by esmanning** [carmls/snacs-guidelines#76]
> Maybe freedom will bring with it progress
task_012
new_doc id = 4c78c7ab-4fd2-4206-342f-22bae20cea4a
sent_id = 2

Guidelines say Locus\~Ancillary for this construction, but only has examples where the two entities would actually be co-located, which doesn't apply in this more abstract/metaphorical sense. Is it still Locus\~Ancillary? If not... Agent\~Ancillary? Ancillary\~Ancillary?

**Comment by nschneid** [comment]
Related to #74

**Comment by nschneid** [comment]
Let's go with **Ensemble~>Ancillary**, following #74.

**Comment by nschneid** [comment]
Add under the current guidelines discussion of "bring with".
