### ISSUE TITLE
work WITH (ambiguous) you

### ISSUE THREAD

**Issue by esmanning** [carmls/snacs-guidelines#77]
Context: poster is giving someone advice on turning down a job offer in favor of doing a PhD:
> As long as you reject the offer with something like listen, I wanted to work WITH you, but ...
task_012
new_doc id = a5c98426-9f68-793e-5634-a8b2610ec605
sent_id = 6

I think 'you' here is most likely the company being turned down, in which case Org~Ancillary?
But it can also be read as referring to an individual potential-coworker.

**Comment by nschneid** [comment]
Just do the best you can with the context!
