### ISSUE TITLE
vs.

### ISSUE THREAD

**Issue by esmanning** [carmls/snacs-guidelines#78]
We've encountered vs. a few times in the Reddit data and generally been a bit confused by it. 

It occurred to me that at least some instances are grouping two things together in a way that may fit the definition of Ensemble, though unlike other Ensemble examples in guidelines, it's not a prototypically-Ancillary preposition. Is that required for Ensemble to apply? Is the non-ancillary-like equivalent just `c?

In any case, I think we would benefit from clearer guidelines on how to treat 'vs.' Here are all the instances of it we've done so far, and how we've annotated them:

> Look at it from a good vs\~`c bad events perspective
task_002
new_doc id = 120961ea-0913-5087-15d3-8ca9986cc8d5
sent_id = 5

> the main problem is you probably lane vs a farming mid
'against opponent' meaning; previously Co-Agent, updated to Agent\~Beneficiary for v2.5
task_002
new_doc id = 90766002-61e0-52c0-d99b-d23589ba5461
sent_id = 1

> The > vs >= is definitely something you can just write and forget about, and when you're testing if you're testing on an account that has like 200 wins, you won't see it.
task_003
doc id = fad32caf-e595-e3cb-07bf-aaea891e53cb
sent_id = 2

> so you can see the actual values of MoP gear VS~ComparisonRef TBC gear in WoLK instances
task_007
new_doc id = 9be3cecb-8c49-7c68-a8c2-4d4244ef7feb
sent_id = 5

> As it is, no warrior vs~`c one is not fun.
task_008
new_doc id = 6e671698-1e83-0596-3646-9fabf59cd100
sent_id = 3

> Ranged vs melee matchups are very onesided in general
Previously co-agent; updating this one is when I started wondering about ensemble, but ¯\_(ツ)_/¯
task_012
new_doc id = a40837a9-f5ce-a353-e90e-2383743444ab
sent_id = 2

>Average zergs absolutely love roach/hydra/corruptor style vs~ComparisonRef protoss as it counters most compositions and requires minimal micro
task_013
new_doc id = 81ee476c-8839-9110-5727-d740fad13805
sent_id = 1

**Comment by nschneid** [comment]
Although dictionaries classify "vs." as a preposition I think it is more commonly a coordinating conjunction. So I would go with `c in the Ensemble-like sense. I think the annotations above look basically good.

**Comment by nschneid** [comment]
I would say the construal it provides as a preposition is force-dynamic in nature, like AGAINST. #21
