### ISSUE TITLE
enemy OF

### ISSUE THREAD

**Issue by esmanning** [carmls/snacs-guidelines#79]
> Ideology is the enemy OF truth , and ideology is the enemy OF facts
task_004
new_doc id = 6db076bd-5980-5a17-2cde-ec51972ab68b
sent_id = 1

These were left blank in the original adjudication in the summer, with the note 'noun metaphor'. Annotators had unanimously said Gestalt so presumably Nathan was uncertain - do we have a better idea what to do with this now?

**Comment by nschneid** [comment]
Theme? X and Y are enemies <-> X is the enemy of Y. "enemy" feels like the main relation here, not a property.

**Comment by nschneid** [comment]
Oh wait I would say SocialRel if we were talking about people. That's why metaphor is relevant.

**Comment by nschneid** [comment]
Eh...SocialRel seems like a bad idea here because we're clearly not talking about people. It is in some sense personification but we'd need a powerful metaphoric reasoning system to make that useful.

"Ideology is truth's enemy"? I can live with Gestalt.

**Comment by esmanning** [comment]
We'll go with Gestalt.
