### ISSUE TITLE
scale TO

### ISSUE THREAD

**Issue by esmanning** [carmls/snacs-guidelines#81]
> You can tell Wowhead to scale the search results TO your desired Timewalking level
task_007
new_doc id = 9be3cecb-8c49-7c68-a8c2-4d4244ef7feb
sent_id = 4

Left blank in original adjudication with note "verb of sizing - hard to distinguish Extent and Goal"

**Comment by nschneid** [comment]
duplicate of #18

**Comment by esmanning** [comment]
oops, sorry!
