### ISSUE TITLE
what's IN this drink

### ISSUE THREAD

**Issue by esmanning** [carmls/snacs-guidelines#83]
> Yeah, plus what 's IN this drink is her pretending to be surprised she was drinking alcohol all along and is tipsy, not her thinking he's roofied her.
Reddit task_005
new_doc id = 27be0381-6544-c97d-e078-9f97213c121c
sent_id = 1

This is about the ongoing controversy about the "What's in this drink?" line from the song Baby It's Cold Outside - it ambiguous between referring to ingredients (~ Is there alcohol in this drink?) vs. implying that something (like a roofie) may have been added to it.

Whole\~Locus? or Locus\~Locus?

**Comment by nschneid** [comment]
Locus~>Locus feels safer if it's ambiguous.
