### ISSUE TITLE
ok FOR X to happen

### ISSUE THREAD

**Issue by esmanning** [carmls/snacs-guidelines#87]
> when is it ok FOR rape [to] occur [in an RPG game]?
Reddit task_010
new_doc id = c2b1c26b-e814-7dc9-af47-9f2936631b3e
sent_id = 16

Theme? Gestalt?

**Comment by nschneid** [comment]
This is infinitival-subject FOR in a cleft sentence. It should be `` `i`` as specified in "Infinitivals with for-subject" section of guidelines.
